### ISSUE TITLE
require error : Cannot find module 'node-ivy'

### ISSUE THREAD

**Issue by doom-fr** [nilpotence/node-ivy#1]
```
module.js:553
    throw err;
    ^

Error: Cannot find module 'node-ivy'
    at Function.Module._resolveFilename (module.js:551:15)
    at Function.Module._load (module.js:495:23)
    at Module.require (module.js:592:17)
    at require (internal/module.js:11:18)
    at self.require (<anonymous>:11:26)
```

adding   `"main": "ivy.js",` in package.json solve the problem.

Thx.

**Comment by doom-fr** [comment]
Merci. Et si ce n'est déjà fait, si tu peux releaser sur npm, cela serait parfait.

**Comment by nilpotence** [comment]
C'est fait ;)
